### ISSUE TITLE
Ignore errors in find

### ISSUE THREAD

**Issue by taopp** [alinex/node-fs#1]
If there's an error(e.g. invalid symlink), the function will throw and break.

**Comment by alinex** [comment]
Did you call the async version fs.find? Then it should return an error in the callback.
Did you call the sync version fs,findSync? Then it should throw an error.

I will make a test szenario for the async fs.find to check if the behaviour is correct in the next days.

**Comment by taopp** [comment]
Oh, it's my fault.
I only invoked the fs.findSync, then I checked into the source code of this function.
Not noticed the different between async version and sync version.

**Comment by taopp** [comment]
I checked the source code again, found my problem still can't be solved even call the async version.
My problem is that if there's an invalid symlink, the function should ignore it and return the rest of result.
Possibly it should better to implement a new function called findFancy or findGrace, when error happened, it catch and continue to get work done.

**Comment by alinex** [comment]
Ok, I got the problem. I will add a option to the find method 'ignoreErrors: true' which won't send the error back but forget it and go on. This is neccessary in case of incorrect symlinks or if permission to read is denied.

**Comment by alinex** [comment]
I just added this option in version 0.2.1 please check this out,
