### ISSUE TITLE
Ignore sub folders finding when parent was excluded.

### ISSUE THREAD

**Issue by taopp** [alinex/node-fs#2]
I think this should be the default behaving of exclud and test options.
If there have a lot of sub folders, say thousands or even millions, This can largely improve performance.

**Comment by alinex** [comment]
For now the new lazy options works great (pull https://github.com/alinex/node-fs/pull/3). But for the future i have to rethink the options structure to allow more powerful selections like:
- logical operators: and, or ,not
- different search patterns for traversing and end matches

**Comment by alinex** [comment]
With version 2.0.4 the lazy option is no longer needed because find will do this on its own. It now detects then a complete directory with all it's files will fail based on the exclude pattern and won't go into this then.

That also makes file traversing faster.
